### ISSUE TITLE
Configure komoot photon server

### ISSUE THREAD

**Issue by davecraig** [Scottish-Tech-Army/Soundscape-Android#352]
For our geo-search during development we have been using the demo photon server. For deployment we'll need our own server. The home page of the project is https://github.com/komoot/photon and there are some simple instructions on installation [here](https://nominatim.org/2020/10/21/photon-country-extracts.html).

The summary is that there are two pieces that need installed:

1. The application itself from https://github.com/komoot/photon/releases
2. The world wide index from https://download1.graphhopper.com/public/

Original postings on platform slack:
> It's trivial to run the photon server locally (see https://nominatim.org/2020/10/21/photon-country-extracts.html) and it just involves downloading a release, downloading the latest photon index (~76GB for the world, or ~3GB for just the UK) and running it. However, there's not a lot of information about the CPU/RAM required to run photon, all I found was https://github.com/komoot/photon/discussions/726.

I did run some [artillery.io](https://www.artillery.io/) testing against a local install and also posted the results
> It took me 20 minutes to get started and run a test against a local photon server using "made up street names" from one of their plugins https://ngneat.github.io/falso/docs/address#randstreetname
I was only running a UK photon index and the memory usage on the server was pretty much just the size of the unzipped index (5.7GB).
https://app.artillery.io/share/sh_20965116282a81feae7b5b1f7ba011ac31884fc9eebb94b30d9f1123830eafda
If I limit the memory that I give the Java process running photon to 1GB then it runs a fair amount slower at peak, but still serving up ~120 requests per seconds which is still way more than I expected. I'm going to download the world index overnight and see how low I can trim the memory when load testing that.

I haven't got as far as load testing the worldwide index, so that still needs looking at.

**Comment by davecraig** [comment]
Note that worldwide indices are very large, the one I downloaded was around 100GB. On linux using bzip2 to decompress the index is very slow, so I'd recommend using pbzip2 (parallel bzip2) which is much faster e.g.

`pbzip2 -dc photon-db-latest.tar.bz2 | tar x`

Or do as it says in the docs (https://github.com/komoot/photon) and decompress as you download:

`wget -O - https://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | pbzip2 -cd | tar x`

**Comment by davecraig** [comment]
For my own help, the initial artillery test I was running used this script (saved as test.yaml):

```
config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http://localhost:2322
  phases:
    - duration: 20
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 20
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 20
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
    fake-data: {}
  apdex:
    threshold: 100
  ensure:
    thresholds:
      - http.response_time.p99: 1000
      - http.response_time.p95: 750
scenarios:
  - flow:
      - loop:
          - get:
              url: '/api?q={{ $randStreetName() }}'
        count: 10
```

Artillery was then run with:
`artillery run test.yaml --record --key MY_API_KEY`

which runs the test locally and then uploaded the results to the cloud. The photon server searches were using a random street name.
